apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "logto.fullname" . }}
  labels:
    {{- include "logto.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "logto.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "logto.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "logto.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: init
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          command:
            - /bin/sh
          args:
            - '-c'
            - 'npm run cli connector add -- --official'
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: connectors
              mountPath: /etc/logto/packages/core/connectors
      containers:
        - name: logto
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: core
              containerPort: {{ .Values.core.port }}
              protocol: TCP
            - name: admin
              containerPort: {{ .Values.admin.port }}
              protocol: TCP
          command:
            - /bin/sh
          args:
            - '-c'
            - 'npm run cli db seed -- --swe && npm start'
          env:
            {{- if .Values.common.env.trustProxyHeader }}
            - name: TRUST_PROXY_HEADER
              value: "1"
            {{- end }}
            - name: NODE_ENV
              value: {{ .Values.common.env.nodeEnv }}
            - name: ENDPOINT
              value: {{ .Values.core.endpoint }}
            - name: ADMIN_ENDPOINT
              value: {{ .Values.admin.endpoint }}
            - name: DB_URL
              value: {{ .Values.common.env.dbURL }}
            {{- if .Values.common.tls.enabled }}
            - name: TLS_CERT_FILE
              value: /etc/tls/tls.crt
            - name: TLS_KEY_FILE
              value: /etc/tls/tls.key
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- if .Values.common.tls.enabled }}
            - name: tls-secret
              mountPath: /etc/tls
              subPath: tls.crt
              readOnly: true
            - name: tls-secret
              mountPath: /etc/tls
              subPath: tls.key
              readOnly: true
            {{- end }}
            - name: connectors
              mountPath: /etc/logto/packages/core/connectors
      volumes:
        - name: connectors
          emptyDir: {}
        {{- if .Values.common.tls.enabled }}
        - name: tls-secret
          secret:
            secretName: {{ .Values.common.tls.secretName }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
