# core service
apiVersion: v1
kind: Service
metadata:
  name: {{ include "logto.fullname" . }}-core
  labels:
    {{- include "logto.labels" . | nindent 4 }}
spec:
  type: {{ .Values.core.service.type }}
  ports:
    - port: {{ .Values.core.service.port }}
      targetPort: core
      protocol: TCP
      name: http
  selector:
    {{- include "logto.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "logto.fullname" . }}-admin
  labels:
    {{- include "logto.labels" . | nindent 4 }}
spec:
  type: {{ .Values.admin.service.type }}
  ports:
    - port: {{ .Values.admin.service.port }}
      targetPort: admin
      protocol: TCP
      name: http
  selector:
    {{- include "logto.selectorLabels" . | nindent 4 }}
