replicaCount: 1

image:
  repository: ghcr.io/logto-io/logto
  pullPolicy: IfNotPresent
  tag: "1.6.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

database:
  enabled: true
  type: postgres
  password: ""

env:
  trustProxyHeader: true
  db_url: ""
  endpoint: ""
  adminEndpoint: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port:
    http: 3001
    api: 3002

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: logto.io
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
