replicaCount: 1

image:
  repository: ghcr.io/logto-io/logto
  pullPolicy: IfNotPresent
  tag: "1.6.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

common:
  tls:
    enabled: false
    secretName: ""
  env:
    nodeEnv: ""
    db_url: postgres://postgres:p0stgr3s@postgres:5432/logto
    adminDisableLocalhost: false
    trustProxyHeader: true

core:
  endpoint: ""
  port: 3001
  service:
    type: ClusterIP
    port: 3001
  ingress:
    enabled: false
    className: ""
    annotations: {}
    hosts:
      - host: logto.io
        paths:
          - path: /
            pathType: Prefix
    tls: []

admin:
  endpoint: ""
  port: 3002
  service:
    type: ClusterIP
    port: 3002
  ingress:
    enabled: false
    className: ""
    annotations: {}
    hosts:
      - host: admin.logto.io
        paths:
          - path: /
            pathType: Prefix
    tls: []

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
